#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-leaflet
Version  : 2.2.0
Release  : 57
URL      : https://cran.r-project.org/src/contrib/leaflet_2.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/leaflet_2.2.0.tar.gz
Summary  : Create Interactive Web Maps with the JavaScript 'Leaflet'
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 MIT
Requires: R-leaflet-license = %{version}-%{release}
Requires: R-RColorBrewer
Requires: R-crosstalk
Requires: R-htmltools
Requires: R-htmlwidgets
Requires: R-jquerylib
Requires: R-leaflet.providers
Requires: R-magrittr
Requires: R-png
Requires: R-raster
Requires: R-scales
Requires: R-sp
Requires: R-viridis
Requires: R-xfun
BuildRequires : R-RColorBrewer
BuildRequires : R-crosstalk
BuildRequires : R-htmltools
BuildRequires : R-htmlwidgets
BuildRequires : R-jquerylib
BuildRequires : R-leaflet.providers
BuildRequires : R-magrittr
BuildRequires : R-png
BuildRequires : R-raster
BuildRequires : R-scales
BuildRequires : R-shiny
BuildRequires : R-sp
BuildRequires : R-viridis
BuildRequires : R-xfun
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
JavaScript library and the 'htmlwidgets' package. These maps can be
    used directly from the R console, from 'RStudio', in Shiny
    applications and R Markdown documents.

%package license
Summary: license components for the R-leaflet package.
Group: Default

%description license
license components for the R-leaflet package.


%prep
%setup -q -n leaflet
pushd ..
cp -a leaflet buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693496593

%install
export SOURCE_DATE_EPOCH=1693496593
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-leaflet
cp %{_builddir}/leaflet/inst/htmlwidgets/lib/leaflet-omnivore/LICENSE %{buildroot}/usr/share/package-licenses/R-leaflet/ce99b89e7b72dc4d2e88e44490128bce8530fb08 || :
cp %{_builddir}/leaflet/inst/htmlwidgets/plugins/Leaflet.EasyButton/LICENSE %{buildroot}/usr/share/package-licenses/R-leaflet/34dcb1162a0e013d42377c846db5ef4cad406ab3 || :
cp %{_builddir}/leaflet/inst/htmlwidgets/plugins/Leaflet.markercluster/MIT-LICENCE.txt %{buildroot}/usr/share/package-licenses/R-leaflet/531bb5cc92d562e31772cd9be8d7c45bfba8c3ba || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/leaflet/DESCRIPTION
/usr/lib64/R/library/leaflet/INDEX
/usr/lib64/R/library/leaflet/Meta/Rd.rds
/usr/lib64/R/library/leaflet/Meta/data.rds
/usr/lib64/R/library/leaflet/Meta/features.rds
/usr/lib64/R/library/leaflet/Meta/hsearch.rds
/usr/lib64/R/library/leaflet/Meta/links.rds
/usr/lib64/R/library/leaflet/Meta/nsInfo.rds
/usr/lib64/R/library/leaflet/Meta/package.rds
/usr/lib64/R/library/leaflet/NAMESPACE
/usr/lib64/R/library/leaflet/NEWS.md
/usr/lib64/R/library/leaflet/R/leaflet
/usr/lib64/R/library/leaflet/R/leaflet.rdb
/usr/lib64/R/library/leaflet/R/leaflet.rdx
/usr/lib64/R/library/leaflet/data/Rdata.rdb
/usr/lib64/R/library/leaflet/data/Rdata.rds
/usr/lib64/R/library/leaflet/data/Rdata.rdx
/usr/lib64/R/library/leaflet/help/AnIndex
/usr/lib64/R/library/leaflet/help/aliases.rds
/usr/lib64/R/library/leaflet/help/leaflet.rdb
/usr/lib64/R/library/leaflet/help/leaflet.rdx
/usr/lib64/R/library/leaflet/help/paths.rds
/usr/lib64/R/library/leaflet/html/00Index.html
/usr/lib64/R/library/leaflet/html/R.css
/usr/lib64/R/library/leaflet/htmlwidgets/assets/leaflet.js
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/cancel.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/cancel_@2X.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/check.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/check_@2X.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/focus.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/focus_@2X.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/rulers.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/rulers_@2X.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/start.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/start_@2X.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/trash.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/images/trash_@2X.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/leaflet-measure.css
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-measure/leaflet-measure.min.js
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-omnivore/LICENSE
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-omnivore/index.js
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-omnivore/leaflet-omnivore.min.js
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet-omnivore/package.json
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet/images/layers-2x.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet/images/layers.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet/images/marker-icon-2x.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet/images/marker-icon.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet/images/marker-shadow.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet/leaflet.css
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leaflet/leaflet.js
/usr/lib64/R/library/leaflet/htmlwidgets/lib/leafletfix/leafletfix.css
/usr/lib64/R/library/leaflet/htmlwidgets/lib/rstudio_leaflet/images/1px.png
/usr/lib64/R/library/leaflet/htmlwidgets/lib/rstudio_leaflet/rstudio_leaflet.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet-MiniMap/Control.MiniMap.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet-MiniMap/Control.MiniMap.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet-MiniMap/Control.MiniMap.min.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet-MiniMap/Control.MiniMap.min.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet-MiniMap/Minimap-binding.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet-MiniMap/images/toggle.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet-MiniMap/images/toggle.svg
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.EasyButton/EasyButton-binding.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.EasyButton/LICENSE
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.EasyButton/easy-button.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.EasyButton/easy-button.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.Graticule/Graticule-binding.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.Graticule/L.Graticule.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.Graticule/Leaflet.Graticule.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.SimpleGraticule/L.SimpleGraticule.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.SimpleGraticule/L.SimpleGraticule.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.SimpleGraticule/SimpleGraticule-binding.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.Terminator/L.Terminator.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.Terminator/Terminator-binding.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/bootstrap-theme.min.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/bootstrap.min.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/bootstrap.min.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/font-awesome.min.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/FontAwesome.otf
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/fontawesome-webfont.eot
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/fontawesome-webfont.svg
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/fontawesome-webfont.ttf
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/fontawesome-webfont.woff
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/glyphicons-halflings-regular.eot
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/glyphicons-halflings-regular.svg
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/glyphicons-halflings-regular.ttf
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/glyphicons-halflings-regular.woff
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/ionicons.eot
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/ionicons.svg
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/ionicons.ttf
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/fonts/ionicons.woff
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/images/markers-matte.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/images/markers-matte@2x.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/images/markers-plain.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/images/markers-shadow.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/images/markers-shadow@2x.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/images/markers-soft.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/images/markers-soft@2x.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/ionicons.min.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/leaflet.awesome-markers.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/leaflet.awesome-markers.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.awesome-markers/leaflet.awesome-markers.min.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.markercluster/MIT-LICENCE.txt
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.markercluster/MarkerCluster.Default.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.markercluster/MarkerCluster.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.markercluster/leaflet.markercluster.freezable.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.markercluster/leaflet.markercluster.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.markercluster/leaflet.markercluster.layersupport.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Leaflet.markercluster/package.json
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Proj4Leaflet/proj4.min.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/Proj4Leaflet/proj4leaflet.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/leaflet-locationfilter/img/filter-icon.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/leaflet-locationfilter/img/move-handle.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/leaflet-locationfilter/img/resize-handle.png
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/leaflet-locationfilter/locationfilter-bindings.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/leaflet-locationfilter/locationfilter.css
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/leaflet-locationfilter/locationfilter.js
/usr/lib64/R/library/leaflet/htmlwidgets/plugins/leaflet-providers-plugin/leaflet-providers-plugin.js
/usr/lib64/R/library/leaflet/legacy/examples/choropleth/DESCRIPTION
/usr/lib64/R/library/leaflet/legacy/examples/choropleth/Rplots.pdf
/usr/lib64/R/library/leaflet/legacy/examples/choropleth/global.R
/usr/lib64/R/library/leaflet/legacy/examples/choropleth/server.R
/usr/lib64/R/library/leaflet/legacy/examples/choropleth/shinyapps/jcheng/choropleth3.dcf
/usr/lib64/R/library/leaflet/legacy/examples/choropleth/ui.R
/usr/lib64/R/library/leaflet/legacy/examples/geojson/server.R
/usr/lib64/R/library/leaflet/legacy/examples/geojson/ui.R
/usr/lib64/R/library/leaflet/legacy/examples/population/server.R
/usr/lib64/R/library/leaflet/legacy/examples/population/ui.R
/usr/lib64/R/library/leaflet/legacy/examples/population/www/styles.css
/usr/lib64/R/library/leaflet/legacy/www/binding.js
/usr/lib64/R/library/leaflet/legacy/www/images/layers-2x.png
/usr/lib64/R/library/leaflet/legacy/www/images/layers.png
/usr/lib64/R/library/leaflet/legacy/www/images/marker-icon-2x.png
/usr/lib64/R/library/leaflet/legacy/www/images/marker-icon.png
/usr/lib64/R/library/leaflet/legacy/www/images/marker-shadow.png
/usr/lib64/R/library/leaflet/legacy/www/leaflet-src.js
/usr/lib64/R/library/leaflet/legacy/www/leaflet.css
/usr/lib64/R/library/leaflet/legacy/www/leaflet.js
/usr/lib64/R/library/leaflet/tests/testthat.R
/usr/lib64/R/library/leaflet/tests/testthat/_snaps/normalize-2.md
/usr/lib64/R/library/leaflet/tests/testthat/_snaps/remote.md
/usr/lib64/R/library/leaflet/tests/testthat/helper.R
/usr/lib64/R/library/leaflet/tests/testthat/test-colors.R
/usr/lib64/R/library/leaflet/tests/testthat/test-evalFormula.R
/usr/lib64/R/library/leaflet/tests/testthat/test-icon.R
/usr/lib64/R/library/leaflet/tests/testthat/test-legend.R
/usr/lib64/R/library/leaflet/tests/testthat/test-measure.R
/usr/lib64/R/library/leaflet/tests/testthat/test-normalize-2.R
/usr/lib64/R/library/leaflet/tests/testthat/test-normalize-3.R
/usr/lib64/R/library/leaflet/tests/testthat/test-normalize.R
/usr/lib64/R/library/leaflet/tests/testthat/test-raster.R
/usr/lib64/R/library/leaflet/tests/testthat/test-remote.R

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-leaflet/34dcb1162a0e013d42377c846db5ef4cad406ab3
/usr/share/package-licenses/R-leaflet/531bb5cc92d562e31772cd9be8d7c45bfba8c3ba
/usr/share/package-licenses/R-leaflet/ce99b89e7b72dc4d2e88e44490128bce8530fb08
